#include "TicoShaders.h"

// ============================================================================
// Vertex Shader (shared by all effects)
// ============================================================================
const char* GetShaderVertexSource()
{
    return
        "#version 330 core\n"
        "layout (location = 0) in vec2 aPos;\n"
        "layout (location = 1) in vec2 aTexCoord;\n"
        "out vec2 TexCoord;\n"
        "void main() {\n"
        "   gl_Position = vec4(aPos, 0.0, 1.0);\n"
        "   TexCoord = aTexCoord;\n"
        "}\n";
}

// ============================================================================
// Fragment Shaders
// ============================================================================

// --- None (passthrough) ---
static const char* kShaderNone =
    "#version 330 core\n"
    "in vec2 TexCoord;\n"
    "out vec4 FragColor;\n"
    "uniform sampler2D Source;\n"
    "void main() {\n"
    "    FragColor = texture(Source, TexCoord);\n"
    "}\n";

// --- Crt Easy Mode (ported from CG) ---
static const char* kShaderCrtEasyMode =
    "#version 330 core\n"
    "in vec2 TexCoord;\n"
    "out vec4 FragColor;\n"
    "uniform sampler2D Source;\n"
    "uniform vec2 TextureSize;\n"
    "uniform vec2 OutputSize;\n"
    "\n"
    "#define SHARPNESS_H 0.5\n"
    "#define SHARPNESS_V 1.0\n"
    "#define MASK_STRENGTH 0.3\n"
    "#define MASK_DOT_WIDTH 1.0\n"
    "#define MASK_DOT_HEIGHT 1.0\n"
    "#define MASK_STAGGER 0.0\n"
    "#define MASK_SIZE 1.0\n"
    "#define SCANLINE_STRENGTH 1.0\n"
    "#define SCANLINE_BEAM_WIDTH_MIN 1.5\n"
    "#define SCANLINE_BEAM_WIDTH_MAX 1.5\n"
    "#define SCANLINE_BRIGHT_MIN 0.35\n"
    "#define SCANLINE_BRIGHT_MAX 0.65\n"
    "#define SCANLINE_CUTOFF 400.0\n"
    "#define GAMMA_INPUT 2.0\n"
    "#define GAMMA_OUTPUT 1.8\n"
    "#define BRIGHT_BOOST 1.2\n"
    "#define DILATION 1.0\n"
    "\n"
    "#define ENABLE_LANCZOS 1\n"
    "#define FIX(c) max(abs(c), 1e-5)\n"
    "#define PI 3.141592653589\n"
    "\n"
    "vec4 dilate(vec4 col) {\n"
    "    vec4 x = mix(vec4(1.0), col, DILATION);\n"
    "    return col * x;\n"
    "}\n"
    "\n"
    "float curve_distance(float x, float sharp) {\n"
    "    float x_step = step(0.5, x);\n"
    "    float curve = 0.5 - sqrt(0.25 - (x - x_step) * (x - x_step)) * sign(0.5 - x);\n"
    "    return mix(x, curve, sharp);\n"
    "}\n"
    "\n"
    "mat4 get_color_matrix(sampler2D tex, vec2 co, vec2 dx) {\n"
    "    return mat4(dilate(texture(tex, co - dx)), dilate(texture(tex, co)), dilate(texture(tex, co + dx)), dilate(texture(tex, co + 2.0 * dx)));\n"
    "}\n"
    "\n"
    "vec3 filter_lanczos(vec4 coeffs, mat4 color_matrix) {\n"
    "    vec4 col = color_matrix * coeffs;\n"
    "    vec4 sample_min = min(color_matrix[1], color_matrix[2]);\n"
    "    vec4 sample_max = max(color_matrix[1], color_matrix[2]);\n"
    "    col = clamp(col, sample_min, sample_max);\n"
    "    return col.rgb;\n"
    "}\n"
    "\n"
    "void main() {\n"
    "    vec2 video_size = TextureSize;\n"
    "    vec2 dx = vec2(1.0 / TextureSize.x, 0.0);\n"
    "    vec2 dy = vec2(0.0, 1.0 / TextureSize.y);\n"
    "    vec2 pix_co = TexCoord * TextureSize - vec2(0.5, 0.5);\n"
    "    vec2 tex_co = (floor(pix_co) + vec2(0.5, 0.5)) / TextureSize;\n"
    "    vec2 dist = fract(pix_co);\n"
    "    float curve_x;\n"
    "    vec3 col, col2;\n"
    "\n"
    "#if ENABLE_LANCZOS\n"
    "    curve_x = curve_distance(dist.x, SHARPNESS_H * SHARPNESS_H);\n"
    "    vec4 coeffs = PI * vec4(1.0 + curve_x, curve_x, 1.0 - curve_x, 2.0 - curve_x);\n"
    "    coeffs = FIX(coeffs);\n"
    "    coeffs = 2.0 * sin(coeffs) * sin(coeffs / 2.0) / (coeffs * coeffs);\n"
    "    coeffs /= dot(coeffs, vec4(1.0));\n"
    "    col = filter_lanczos(coeffs, get_color_matrix(Source, tex_co, dx));\n"
    "    col2 = filter_lanczos(coeffs, get_color_matrix(Source, tex_co + dy, dx));\n"
    "#else\n"
    "    curve_x = curve_distance(dist.x, SHARPNESS_H);\n"
    "    col = mix(texture(Source, tex_co).rgb, texture(Source, tex_co + dx).rgb, curve_x);\n"
    "    col2 = mix(texture(Source, tex_co + dy).rgb, texture(Source, tex_co + dx + dy).rgb, curve_x);\n"
    "#endif\n"
    "\n"
    "    col = mix(col, col2, curve_distance(dist.y, SHARPNESS_V));\n"
    "    col = pow(col, vec3(GAMMA_INPUT / (DILATION + 1.0)));\n"
    "\n"
    "    float luma = dot(vec3(0.2126, 0.7152, 0.0722), col);\n"
    "    float bright = (max(col.r, max(col.g, col.b)) + luma) / 2.0;\n"
    "    float scan_bright = clamp(bright, SCANLINE_BRIGHT_MIN, SCANLINE_BRIGHT_MAX);\n"
    "    float scan_beam = clamp(bright * SCANLINE_BEAM_WIDTH_MAX, SCANLINE_BEAM_WIDTH_MIN, SCANLINE_BEAM_WIDTH_MAX);\n"
    "    float scan_weight = 1.0 - pow(cos(TexCoord.y * 2.0 * PI * TextureSize.y) * 0.5 + 0.5, scan_beam) * SCANLINE_STRENGTH;\n"
    "\n"
    "    float mask = 1.0 - MASK_STRENGTH;\n"
    "    vec2 mod_fac = floor(TexCoord * OutputSize * TextureSize / (video_size * vec2(MASK_SIZE, MASK_DOT_HEIGHT * MASK_SIZE)));\n"
    "    int dot_no = int(mod((mod_fac.x + mod(mod_fac.y, 2.0) * MASK_STAGGER) / MASK_DOT_WIDTH, 3.0));\n"
    "    vec3 mask_weight;\n"
    "\n"
    "    if (dot_no == 0) mask_weight = vec3(1.0, mask, mask);\n"
    "    else if (dot_no == 1) mask_weight = vec3(mask, 1.0, mask);\n"
    "    else mask_weight = vec3(mask, mask, 1.0);\n"
    "\n"
    "    if (video_size.y >= SCANLINE_CUTOFF) scan_weight = 1.0;\n"
    "\n"
    "    col2 = col.rgb;\n"
    "    col *= vec3(scan_weight);\n"
    "    col = mix(col, col2, scan_bright);\n"
    "    col *= mask_weight;\n"
    "    col = pow(col, vec3(1.0 / GAMMA_OUTPUT));\n"
    "\n"
    "    FragColor = vec4(col * BRIGHT_BOOST, 1.0);\n"
    "}\n";

// --- xBRZ (simplified single-pass xBR upscaler) ---
static const char* kShaderXBRZ =
    "#version 330 core\n"
    "in vec2 TexCoord;\n"
    "out vec4 FragColor;\n"
    "uniform sampler2D Source;\n"
    "uniform vec2 TextureSize;\n"
    "uniform vec2 OutputSize;\n"
    "\n"
    "#define EQ_THRESHOLD 15.0/255.0\n"
    "\n"
    "float cdist(vec4 A, vec4 B) {\n"
    "    vec4 diff = A - B;\n"
    "    return dot(diff, diff);\n"
    "}\n"
    "bool is_eq(vec4 A, vec4 B) {\n"
    "    return cdist(A, B) < EQ_THRESHOLD;\n"
    "}\n"
    "\n"
    "void main() {\n"
    "    vec2 pos = TexCoord * TextureSize;\n"
    "    vec2 f = fract(pos);\n"
    "    vec2 dx = vec2(1.0 / TextureSize.x, 0.0);\n"
    "    vec2 dy = vec2(0.0, 1.0 / TextureSize.y);\n"
    "    vec4 E = texture(Source, TexCoord);\n"
    "    vec4 B = texture(Source, TexCoord - dy);\n"
    "    vec4 D = texture(Source, TexCoord - dx);\n"
    "    vec4 F = texture(Source, TexCoord + dx);\n"
    "    vec4 H = texture(Source, TexCoord + dy);\n"
    "    vec4 res = E;\n"
    "    bool eLDiff = (B != H && D != F);\n"
    "    if (eLDiff) {\n"
    "        if (is_eq(D,B) && !is_eq(D,H) && !is_eq(B,F) && f.x < 0.5 && f.y < 0.5) res = D;\n"
    "        if (is_eq(B,F) && !is_eq(B,D) && !is_eq(F,H) && f.x >= 0.5 && f.y < 0.5) res = F;\n"
    "        if (is_eq(D,H) && !is_eq(D,B) && !is_eq(H,F) && f.x < 0.5 && f.y >= 0.5) res = D;\n"
    "        if (is_eq(H,F) && !is_eq(H,D) && !is_eq(F,B) && f.x >= 0.5 && f.y >= 0.5) res = F;\n"
    "    }\n"
    "    FragColor = res;\n"
    "}\n";



// --- Eagle ---
static const char* kShaderEagle =
    "#version 330 core\n"
    "in vec2 TexCoord;\n"
    "out vec4 FragColor;\n"
    "uniform sampler2D Source;\n"
    "uniform vec2 TextureSize;\n"
    "uniform vec2 OutputSize;\n"
    "\n"
    "vec3 dtt = vec3(65536.0, 255.0, 1.0);\n"
    "float reduce(vec3 color) { return dot(color, dtt); }\n"
    "\n"
    "int GET_RESULT(float A, float B, float C, float D) {\n"
    "    int x = 0, y = 0, r = 0;\n"
    "    if (A == C) x++; else if (B == C) y++;\n"
    "    if (A == D) x++; else if (B == D) y++;\n"
    "    if (x <= 1) r++;\n"
    "    if (y <= 1) r--;\n"
    "    return r;\n"
    "}\n"
    "\n"
    "void main() {\n"
    "    vec2 texel = 1.0 / TextureSize;\n"
    "    float dx = texel.x;\n"
    "    float dy = texel.y;\n"
    "    vec2 fp = fract(TexCoord * TextureSize);\n"
    "\n"
    "    vec3 C0 = texture(Source, TexCoord + vec2(-dx, -dy)).rgb;\n"
    "    vec3 C1 = texture(Source, TexCoord + vec2(-dx,   0)).rgb;\n"
    "    vec3 C2 = texture(Source, TexCoord + vec2( dx, -dy)).rgb;\n"
    "    vec3 D3 = texture(Source, TexCoord + vec2(dx+dx,-dy)).rgb;\n"
    "    vec3 C3 = texture(Source, TexCoord + vec2(-dx,   0)).rgb;\n"
    "    vec3 C4 = texture(Source, TexCoord).rgb;\n"
    "    vec3 C5 = texture(Source, TexCoord + vec2( dx,   0)).rgb;\n"
    "    vec3 D4 = texture(Source, TexCoord + vec2(dx+dx, 0)).rgb;\n"
    "    vec3 C6 = texture(Source, TexCoord + vec2(-dx,  dy)).rgb;\n"
    "    vec3 C7 = texture(Source, TexCoord + vec2(  0,  dy)).rgb;\n"
    "    vec3 C8 = texture(Source, TexCoord + vec2( dx,  dy)).rgb;\n"
    "    vec3 D5 = texture(Source, TexCoord + vec2(dx+dx,dy)).rgb;\n"
    "    vec3 D0 = texture(Source, TexCoord + vec2(-dx,dy+dy)).rgb;\n"
    "    vec3 D1 = texture(Source, TexCoord + vec2(  0,dy+dy)).rgb;\n"
    "    vec3 D2 = texture(Source, TexCoord + vec2( dx,dy+dy)).rgb;\n"
    "    vec3 D6 = texture(Source, TexCoord + vec2(dx+dx,dy+dy)).rgb;\n"
    "\n"
    "    float c0=reduce(C0); float c1=reduce(C1); float c2=reduce(C2);\n"
    "    float c3=reduce(C3); float c4=reduce(C4); float c5=reduce(C5);\n"
    "    float c6=reduce(C6); float c7=reduce(C7); float c8=reduce(C8);\n"
    "    float d0=reduce(D0); float d1=reduce(D1); float d2=reduce(D2);\n"
    "    float d3=reduce(D3); float d4=reduce(D4); float d5=reduce(D5);\n"
    "    float d6=reduce(D6);\n"
    "\n"
    "    vec3 p00, p10, p01, p11;\n"
    "    if (c4 != c8) {\n"
    "        if (c7 == c5) {\n"
    "            p01 = C7; p10 = C7;\n"
    "            if ((c6==c7)||(c5==c2)) p00 = 0.25*(3.0*C7+C4);\n"
    "            else p00 = 0.5*(C4+C5);\n"
    "            if ((c5==d4)||(c7==d1)) p11 = 0.25*(3.0*C7+C8);\n"
    "            else p11 = 0.5*(C7+C8);\n"
    "        } else {\n"
    "            p11 = 0.125*(6.0*C8+C7+C5);\n"
    "            p00 = 0.125*(6.0*C4+C7+C5);\n"
    "            p10 = 0.125*(6.0*C7+C4+C8);\n"
    "            p01 = 0.125*(6.0*C5+C4+C8);\n"
    "        }\n"
    "    } else {\n"
    "        if (c7 != c5) {\n"
    "            p11 = C4; p00 = C4;\n"
    "            if ((c1==c4)||(c8==d5)) p01 = 0.25*(3.0*C4+C5);\n"
    "            else p01 = 0.5*(C4+C5);\n"
    "            if ((c8==d2)||(c3==c4)) p10 = 0.25*(3.0*C4+C7);\n"
    "            else p10 = 0.5*(C7+C8);\n"
    "        } else {\n"
    "            int r = 0;\n"
    "            r += GET_RESULT(c5,c4,c6,d1);\n"
    "            r += GET_RESULT(c5,c4,c3,c1);\n"
    "            r += GET_RESULT(c5,c4,d2,d5);\n"
    "            r += GET_RESULT(c5,c4,c2,d4);\n"
    "            if (r > 0) { p01=C7; p10=C7; p00=0.5*(C4+C5); p11=0.5*(C4+C5); }\n"
    "            else if (r < 0) { p11=C4; p00=C4; p01=0.5*(C4+C5); p10=0.5*(C4+C5); }\n"
    "            else { p11=C4; p00=C4; p01=C7; p10=C7; }\n"
    "        }\n"
    "    }\n"
    "    vec3 res = (fp.x < 0.5) ? (fp.y < 0.5 ? p00 : p10) : (fp.y < 0.5 ? p01 : p11);\n"
    "    FragColor = vec4(res, 1.0);\n"
    "}\n";



// ============================================================================
// Fragment Shader Dispatch
// ============================================================================
const char* GetShaderFragmentSource(ShaderType type)
{
    switch (type)
    {
    case ShaderType::xBRZ:               return kShaderXBRZ;
    case ShaderType::Eagle:              return kShaderEagle;
    case ShaderType::CrtEasyMode:        return kShaderCrtEasyMode;
    case ShaderType::None:
    default:                             return kShaderNone;
    }
}
